import type {
  Announcement,
  CurrentUser,
  EventItem,
  Registration,
  Role,
} from '@/lib/types'


export const COLLEGE_NAME = 'IMS Engineering College'

export const currentUser: CurrentUser = {
  name: 'Aarav Menon',
  email: 'aarav.menon@sit.edu.in',
  college: COLLEGE_NAME,
  department: 'Computer Science',
  year: '3rd Year',
  rollNumber: 'SIT21CS042',
  phone: '98765 43210',
  role: 'student',
}

export const demoUsers: Record<Role, CurrentUser> = {
  student: {
    name: 'Aarav Menon',
    email: 'aarav.menon@sit.edu.in',
    college: COLLEGE_NAME,
    department: 'Computer Science',
    year: '3rd Year',
    rollNumber: 'SIT21CS042',
    phone: '98765 43210',
    role: 'student',
  },
  organizer: {
    name: 'Prof. Meera Sharma',
    email: 'meera.organizer@sit.edu.in',
    college: COLLEGE_NAME,
    department: 'Computer Science & Innovation Cell',
    year: 'Faculty Lead',
    rollNumber: 'ORG-FAC-809',
    phone: '98765 11223',
    role: 'organizer',
  },
  admin: {
    name: 'Dr. Rajesh Varma',
    email: 'admin.dean@sit.edu.in',
    college: COLLEGE_NAME,
    department: 'Office of Dean Academic Affairs',
    year: 'Administration',
    rollNumber: 'ADM-DEAN-001',
    phone: '98765 99000',
    role: 'admin',
  },
}

export const seedEvents: EventItem[] = [
  {
    id: 'ev-hackathon',
    title: 'CodeStorm 24-Hour Hackathon',
    tagline: 'Build something that matters, overnight.',
    description:
      'A flagship 24-hour build sprint where teams ship a working prototype around open problem statements in health, campus life and climate. Mentors from the industry review progress every six hours, and the final demo runs on the main stage.',
    category: 'Technical',
    status: 'upcoming',
    date: '2026-08-21',
    startTime: '09:00',
    endTime: '10:00',
    venue: 'Innovation Block, Lab 4',
    department: 'Computer Science',
    organizer: 'Coding Club',
    capacity: 240,
    fee: 150,
    teamEvent: true,
    teamSize: 4,
    prize: 'Rs. 60,000 pool',
    image: '/events/hackathon.png',
    tags: ['Hackathon', 'Team', 'Overnight', 'Mentors'],
  },
  {
    id: 'ev-cultural',
    title: 'Rhythmix Cultural Night',
    tagline: 'The night the campus dances.',
    description:
      'The headline cultural evening of the annual fest with group dance, solo classical, fashion walk and a celebrity closing act. Slot times are allotted automatically based on registration order and category.',
    category: 'Cultural',
    status: 'upcoming',
    date: '2026-08-29',
    startTime: '17:30',
    endTime: '22:00',
    venue: 'Open Air Amphitheatre',
    department: 'Student Affairs',
    organizer: 'Cultural Committee',
    capacity: 1200,
    fee: 0,
    teamEvent: true,
    teamSize: 8,
    prize: 'Rolling trophy',
    image: '/events/cultural-night.png',
    tags: ['Dance', 'Music', 'Fashion', 'Main Stage'],
  },
  {
    id: 'ev-robotics',
    title: 'RoboSprint Line Follower Challenge',
    tagline: 'Fastest bot on the track takes it all.',
    description:
      'Bring your own bot and race it through a timed line-following circuit with three difficulty laps. Scrutiny happens at the pit desk, and the leaderboard updates live after every heat.',
    category: 'Technical',
    status: 'live',
    date: '2026-08-01',
    startTime: '10:00',
    endTime: '16:30',
    venue: 'Mechanical Workshop Arena',
    department: 'Mechatronics',
    organizer: 'Robotics Society',
    capacity: 120,
    fee: 200,
    teamEvent: true,
    teamSize: 3,
    prize: 'Rs. 25,000 pool',
    image: '/events/robotics.png',
    tags: ['Robotics', 'Arena', 'Live Scoring'],
  },
  {
    id: 'ev-uiux',
    title: 'Pixel Craft UI/UX Designathon',
    tagline: 'Design accessible campus solutions in 4 hours.',
    description:
      'A focused sprint to redesign one real-world student portal touchpoint. Participants deliver Figma prototypes evaluated on usability, accessibility contrast and design system consistency.',
    category: 'Workshop',
    status: 'upcoming',
    date: '2026-08-14',
    startTime: '11:00',
    endTime: '15:00',
    venue: 'Design Studio 2',
    department: 'Information Technology',
    organizer: 'Design Guild',
    capacity: 80,
    fee: 50,
    teamEvent: false,
    teamSize: 1,
    prize: 'Figma Subscriptions + Goodies',
    image: '/events/designathon.png',
    tags: ['Figma', 'UI/UX', 'Sprint', 'Solo'],
  },
  {
    id: 'ev-battlebands',
    title: 'Battle of the Bands',
    tagline: 'Eight bands, one encore.',
    description:
      'Inter-college band championship featuring rock, metal and fusion genres. Each band gets a 20-minute stage slot evaluated on originality, stage presence and crowd engagement.',
    category: 'Cultural',
    status: 'upcoming',
    date: '2026-08-18',
    startTime: '18:00',
    endTime: '22:30',
    venue: 'Quadrangle Stage',
    department: 'Music Society',
    organizer: 'Octave Club',
    capacity: 800,
    fee: 50,
    teamEvent: true,
    teamSize: 6,
    prize: 'Rs. 40,000 + Studio Recording Time',
    image: '/events/battle-of-bands.png',
    tags: ['Music', 'Live Band', 'Stage', 'Competition'],
  },
  {
    id: 'ev-esports',
    title: 'Valorant Campus Championship',
    tagline: '5v5 tactical shooter tournament.',
    description:
      'LAN tournament played on dedicated tournament servers with live shoutcasting in the auditorium. Double elimination bracket with custom lobby settings.',
    category: 'Gaming',
    status: 'upcoming',
    date: '2026-08-25',
    startTime: '13:00',
    endTime: '20:00',
    venue: 'Seminar Hall A',
    department: 'Esports Alliance',
    organizer: 'GG Campus',
    capacity: 160,
    fee: 250,
    teamEvent: true,
    teamSize: 5,
    prize: 'Rs. 25,000',
    image: '/events/esports.png',
    tags: ['Esports', 'Valorant', 'LAN', 'Shoutcast'],
  },
  {
    id: 'ev-sports',
    title: 'Inter-Department Football Cup',
    tagline: 'Pride, passion and 90 minutes on the turf.',
    description:
      'Annual 7-a-side football tournament for department teams. Knockout matches played under floodlights with official FIFA-certified student referees.',
    category: 'Sports',
    status: 'completed',
    date: '2026-07-20',
    startTime: '16:00',
    endTime: '20:00',
    venue: 'Sports Complex Turf',
    department: 'Physical Education',
    organizer: 'Sports Council',
    capacity: 300,
    fee: 0,
    teamEvent: true,
    teamSize: 10,
    prize: 'Championship Trophy',
    image: '/events/football-cup.png',
    tags: ['Football', 'Turf', 'Knockout', 'Sports'],
  },
  {
    id: 'ev-ai-workshop',
    title: 'Generative AI & LLM Deployment Workshop',
    tagline: 'From prompt engineering to production APIs.',
    description:
      'Hands-on masterclass building RAG pipelines using LangChain, FastHTML and local LLM backends. Laptop with Python 3.10+ required for hands-on labs.',
    category: 'Workshop',
    status: 'completed',
    date: '2026-07-25',
    startTime: '10:00',
    endTime: '16:00',
    venue: 'Central Computing Center',
    department: 'Computer Science',
    organizer: 'AI Research Group',
    capacity: 100,
    fee: 100,
    teamEvent: false,
    teamSize: 1,
    prize: 'Certificate of Completion',
    image: '/events/ai-workshop.png',
    tags: ['AI', 'LLMs', 'Python', 'Hands-on'],
  },
]

export const myseedRegistrations: Registration[] = [
  {
    id: 'reg-001',
    code: 'SIT-CODESTORM-042',
    eventId: 'ev-hackathon',
    name: 'Aarav Menon',
    email: 'aarav.menon@sit.edu.in',
    phone: '98765 43210',
    college: COLLEGE_NAME,
    department: 'Computer Science',
    year: '3rd Year',
    rollNumber: 'SIT21CS042',
    registeredAt: '2026-07-15T10:30:00Z',
    checkedIn: false,
    paid: true,
    teamName: 'Neural Ninjas',
  },
  {
    id: 'reg-002',
    code: 'SIT-BANDS-042',
    eventId: 'ev-battlebands',
    name: 'Aarav Menon',
    email: 'aarav.menon@sit.edu.in',
    phone: '98765 43210',
    college: COLLEGE_NAME,
    department: 'Computer Science',
    year: '3rd Year',
    rollNumber: 'SIT21CS042',
    registeredAt: '2026-07-18T14:15:00Z',
    checkedIn: false,
    paid: true,
  },
]

export const seedRegistrations: Registration[] = [
  {
    id: 'reg-003',
    code: 'SIT-ROBO-015',
    eventId: 'ev-robotics',
    name: 'Ananya Roy',
    email: 'ananya.roy@sit.edu.in',
    phone: '98765 11111',
    college: COLLEGE_NAME,
    department: 'Electronics',
    year: '2nd Year',
    rollNumber: 'SIT22EC015',
    registeredAt: '2026-07-20T09:00:00Z',
    checkedIn: true,
    checkedInAt: '2026-08-01T10:15:00Z',
    paid: true,
  },
  {
    id: 'reg-004',
    code: 'SIT-ROBO-088',
    eventId: 'ev-robotics',
    name: 'Rohan Verma',
    email: 'rohan.v@sit.edu.in',
    phone: '98765 22222',
    college: COLLEGE_NAME,
    department: 'Mechanical',
    year: '3rd Year',
    rollNumber: 'SIT21ME088',
    registeredAt: '2026-07-21T11:40:00Z',
    checkedIn: true,
    checkedInAt: '2026-08-01T10:22:00Z',
    paid: true,
  },
]

export const seedAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'CodeStorm Problem Statements Released',
    message:
      'All team leads can now view the domain tracks under My Passes. Mentorship slots open tomorrow at 10 AM.',
    eventId: 'ev-hackathon',
    createdAt: '2026-07-28T08:00:00Z',
    read: false,
    priority: 'urgent',
  },
  {
    id: 'ann-2',
    title: 'Line Follower Calibration Track Open',
    message:
      'The practice track in the mechanical workshop is open for sensor calibration till 6 PM today.',
    eventId: 'ev-robotics',
    createdAt: '2026-07-31T09:30:00Z',
    read: false,
    priority: 'normal',
  },
  {
    id: 'ann-3',
    title: 'Campus Entry Guidelines for Fest Week',
    message:
      'Please keep your SIT digital pass QR code handy at gate 2 for fast-track entry.',
    eventId: 'all',
    createdAt: '2026-07-30T12:00:00Z',
    read: true,
    priority: 'normal',
  },
]
